reporting-disabled = false
dir = ""
bind-address = ":8088"

[meta]
  enabled = true
  dir = "/data/meta"
  bind-address = ":8088"
  http-bind-address = ":8091"
  https-enabled = false
  https-certificate = ""
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"
  cluster-tracing = false
  raft-promotion-enabled = true
  logging-enabled = false
  pprof-enabled = false
  lease-duration = "1m0s"

[data]
  enabled = true
  dir = "/data/db"
  engine = "tsm1"
  max-wal-size = 104857600
  wal-flush-interval = "10m0s"
  wal-partition-flush-delay = "2s"
  wal-dir = "/data/db/wal"
  wal-logging-enabled = false
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "5s"
  wal-partition-size-threshold = 52428800
  query-log-enabled = false
  cache-max-memory-size = 1048576000
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "10m0s"
  compact-full-write-cold-duration = "4h0m0s"
  max-points-per-block = 0
  data-logging-enabled = false

[coordinator]
  force-remote-mapping = false
  write-timeout = "5s"
  shard-writer-timeout = "5s"
  shard-mapper-timeout = "5s"

[retention]
  enabled = true
  check-interval = "30m0s"

[shard-precreation]
  enabled = true
  check-interval = "10m0s"
  advance-period = "30m0s"

[monitor]
  store-enabled = true
  store-database = "_internal"
  store-interval = "10s"

[subscriber]
  enabled = true

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = false
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  flux-enabled = true


[continuous_queries]
  log-enabled = false
  enabled = true
  run-interval = "1s"

[hinted-handoff]
  enabled = true
  dir = "/home/influxdb/.influxdb/hh"
  max-size = 1073741824
  max-age = "168h0m0s"
  retry-rate-limit = 0
  retry-interval = "1s"
  retry-max-interval = "1m0s"
  purge-interval = "1h0m0s"

[[graphite]]
  enabled = false
  bind-address = ":2003"
  protocol = "tcp"
  consistency-level = "one"
  separator = "."



[[udp]]
  enabled = false
  bind-address = ":8089"
  database = "udp"
  batch-size = 1000
  batch-timeout = "1s"
  batch-pending = 5
  read-buffer =0
