version: "2"
services:
  postgres:
    image: postgres:10
    container_name: local_postgresql
    restart: always
    privileged: true
    environment:
    -  POSTGRES_USER=postgres
    -  POSTGRES_PASSWORD=123456
    -  PGDATA=/var/lib/postgresql/data
    ports:
    - 5432:5432
    volumes:
    - /data/postgresql:/var/lib/postgresql/data
networks:
  default:
    external:
      name: web

